name: test
on:
  issue_comment:
    types: [created, deleted]

  pull_request:
    types:
      - labeled
    branches:
      - main

jobs:
  bar:
    runs-on: "ubuntu-latest"
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
