name: test
on:
  issue_comment:
    types: [created, deleted]

  pull_request:
    types:
      - labeled
    branches:
      - main

jobs:
  bar:
    runs-on: "ubuntu-latest"
    steps:
      - name: Dump GitHub context
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput('context', JSON.stringify(github.context))

